### ISSUE TITLE
Use github-pages gem for matching build environment

### ISSUE THREAD

**Issue by pedrovereza** [pixelated-project/pixelated-project.github.io#17]
As the website is built by GitHub Pages, it's recommended to use ``github-pages`` gem in order to have a local build environment that matches the one used by GitHub Pages.

More info here: https://github.com/github/pages-gem
and here: https://help.github.com/articles/using-jekyll-with-pages/

**Comment by bwgpro** [comment]
We had to stop using github pages because we couldn't reliably use https there, the website is now running on our host, even though the project name wasn't changed to match that.

We are using only jekyll now and we have to change the README to reflect that

**Comment by pedrovereza** [comment]
Makes sense. I'll close this one, thanks!
