### ISSUE TITLE
Provide commercial cert try.pixelated-project.org

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-project.github.io#20]
## Why

Right now users are getting a message saying that the certificate is invalid (NET::ERR_CERT_AUTHORITY_INVALID) when coming to try.pixelated-project for the first time. This may turn some people away, look bad to others and generally "teach" people the wrong behaviour. We should lower the barrier of entry for new users.

## Definition of done
A new user coming to https://try.pixelated-project.org or https://try.pixelated-project.org:8080 does not see this message, the HTTPS certificate is working and the site is accessible normally.

---
### Previous desciription
@varac: We should not confuse users with security warnings browsing to https://try.pixelated-project.org:8080/, so the only solution i see is to buy a cert.

**Other notes are displayed normally below**

**Comment by lqust** [comment]
We discussed providing our fingerprint on the site instead. That would probably be a better message then telling potential users to trust "big CAs". Maybe we could have a short text on why/how when you click on "Look".

**Comment by lieblingswelt** [comment]
We need to decide whether we want a wildcard cert or individual certs.

**Comment by varac** [comment]
one argument for a wildcard cert would be that we need a valid cert for hub.pix as well (https://github.com/pixelated-project/project-issues/issues/53)

**Comment by varac** [comment]
blocked, waiting for @erikdoe to buy it

**Comment by erikdoe** [comment]
Do we want a wildcard cert for all of pixelated-project.org? Or just a specific one for try?

**Comment by bwgpro** [comment]
@erikdoe We decided for a wildcard cert because we have more subdomains under pixelated now like try.pixelated-project.org and packages.pixelated-project.org

**Comment by cz8s** [comment]
we have a valid cert for *.pixelated-project.org now.
I put it into puppet. 
Todo: Install on try

**Comment by cz8s** [comment]
cert is installed on try.pixelated
Can be validated by going to https://try.pixelated-project.org and seeing that the location-bar is green

**Comment by cz8s** [comment]
the user-agent and disptacher can't handle the new cert; 
See https://github.com/pixelated-project/pixelated-dispatcher/issues/93
and https://github.com/pixelated-project/pixelated-user-agent/issues/333

**Comment by cz8s** [comment]
I installed the cert and told only the dispatcher-proxy to use it.
So visitors to try:8080 get the valid cert, but leap uses the invalid certs internally.
That is why we still have invalid certificates on try:443
