### ISSUE TITLE
Architecture section on pixelated-project.org

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-project.github.io#22]
We want to show the high level Architecture on the website,
so that a visitor to the website can get a broad understanding of the overall Architecture. 
As a visitor to the website, I want to be able to go straight to the separate Github repositories' readme's when clicking on the respective elements in the overview.

- graphics for overview (website) and individual repos are available. see: https://github.com/pixelated-project/project-issues/issues/80

This story involves 
- adding architecture section to the website's main site 
- linking from the architecture's elements to the respective Github readme's

Excluded:
- adding dispatcher- and user-agent detail overviews to the github repos' readmes (https://github.com/pixelated-project/project-issues/issues/85)

**Comment by lieblingswelt** [comment]
Is fine. Do we want to link from leap platform to Leap documentation of single node email provider?: https://leap.se/en/docs/platform/tutorials/single-node-email

**Comment by albogabriel** [comment]
LEAP properly linked! I'll now work on links visibility as part of a separate issue.
