### ISSUE TITLE
Show information about the crypto we use on the website

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-project.github.io#25]
## Why
As a potential User I want to know what kind of crypto pixelated is using and why I should trust it with my mails. Currently we have no information whatsoever on our homepage aside from mentioning LEAP. It would be nice to at least have  a brief overview what kind of crypto pixelated uses, whats encrypted and what is not.

## Definition of done
* When I go to the pixelated project website Then I see I see a link about 'what encryption do we use'
* When I click on that link Then I get to a native page (not LEAP's one) that explains the crypto libraries and tools and how they are used

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
